[project]
name = "plotly-express-resources"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "kaleido==0.2.1",
    "nbformat>=5.10.4",
    "pandas>=2.2.3",
    "plotly[express]>=6.0.1",
]
